### ISSUE TITLE
Warning: repl(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by netfly** [jesusoterogomez/react-notify-toast#1] opened 2015-10-27 20:08 UTC
Sorry, I'm pretty new to React, but I already used a lot of 3rd party components and never had any problems.
Do you have any idea, whats the problem here?

In the console log I see this two warnings/erros
Warning: repl(...): React component classes must extend React.Component.
Uncaught Error: Invariant Violation: repl.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

thnx for your help
Markus

**Comment by jesusoterogomez** [comment] 2015-10-29 09:23
Could you show me your use case?. 

I installed the component in a newly created project. and it works properly. Probably the documentation needs some improvement though :smile: 

Let's suppose that I render the something from a file with this structure
```
import React from 'react';
import Notifications, {notify} from 'react-notify-toast'; 

export default React.createClass({
  handleShowNotification(e) {
     notify.show('This is a nice toast!', 'success');
  },

  render() {
    return (
      <div>
          <Notifications /> {/* Renders the container for the notifications */}
          <button onClick="this.handleShowNotification">Show Notification!</button>
      </div>
    );
  }
});
```

This would be enough to make the notifications work, as `Notifications` is the component that is being used to render the toasts and {notify} contains the reference to the function that creates and animates the notifications.

By the way, sorry for not replying sooner, the issue was hidden among many notifications and I just noticed I had it, I'll be more diligent from now on.

As for your initial issue, could it be something `react-router-component` related? this is what I could find about it. https://github.com/STRML/react-router-component/issues/102 . If you're not using any of that, could you try to help me reproduce the issue?

**Comment by ipanasenko** [comment] 2016-02-11 15:38
Hi!
I have the same issue, and I got steps to reproduce. It's easy:

1. Get this boilerplate: https://github.com/srn/react-webpack-boilerplate
2. Use `Notifications` component in, lets say, `Index.jsx`
3. See error: https://dl.dropboxusercontent.com/spa/lzmr7lr81mgaoil/k1glx5ia.png

Index.jsx code:
```javascript
import React, {Component} from 'react';
import Notifications, {notify} from 'react-notify-toast';

export default class extends Component {
  render() {
    return (
      <section>
        <Notifications/>
        <button onClick={()=>{notify.show('notification!')}}>click me</button>
      </section>
    );
  }
}
```

**Comment by ipanasenko** [comment] 2016-02-11 15:45
Must be an issue with babel-compiled version in `dist`. Including `src/notify.js` works fine.
However, there are a couple of warnings in console: https://dl.dropboxusercontent.com/spa/lzmr7lr81mgaoil/jqv0f2uw.png

I will try to provide a PR to fix something in a couple of days

Cheers

**Comment by ipanasenko** [comment] 2016-02-11 17:11
PR: https://github.com/jesusoterogomez/react-notify-toast/pull/3

**Comment by rbarman** [comment] 2016-02-17 18:27
I am also running into this issue. @ipanasenko were you able to get a fix for this?

**Comment by ipanasenko** [comment] 2016-02-17 18:30
I provided PR that should fix it. issue was in dependencies mostly

**Comment by jesusoterogomez** [comment] 2016-02-17 18:35
@ipanasenko @rbarman 
I will merge PR #3 . This issue is due that currently, this component supports legacy React versions.
However, I will tidy it in the upcoming days. I have to check if this allows backwards compatibility. since I am using it in a `React < 0.13.3` project.

**Closed** 2016-02-17 18:36 UTC
